### PR TITLE
2 fullscreen screenshots of a basic configuration with 2 and 4 decks,…

### PR DESCRIPTION
**Pull request by m0dB**
… latenight

### CODE REVIEW

**Comment by ronso0** [comment]
Thank you!

I'm not sure how to update the screenshots page. (I'm web dev noob)
Other pages' edits are done in the respective md files, though apparently the screenshots page was last updated before the website backend migration.

@Holzhaus 
Shall we update screenshots.html manually, or what's the preferred way here?
https://github.com/mixxxdj/website/blob/website/theme/templates/pages/screenshots.html

**Comment by Swiftb0y** [comment]
> Shall we update screenshots.html manually, or what's the preferred way here?

Pretty sure just update the screenshots html directly, adjusting path and figcaption. also, we'd need a low and high res version of each screenshot respectively.

**Comment by ronso0** [comment]
@m0dB I think there's something wrong with the colors here, the orange leans more towards red
2.3 screenshot https://mixxx.org/theme/images/2.3/screenshots/latenight-palemoon-3840x2160.png
image

This PR
image

**Comment by m0dB** [comment]
Welcome to the wonderful world of png profiles! On my screen it definitely doesn't look that red. Let me see if I can save it with a different color profile, and what color profile that should be...

**Comment by m0dB** [comment]
@ronso0 does it look better now? 

FWIW, I used ImageMagick with ```convert $filename -profile sRGB.icc +profile "*" $filename```

@Swiftb0y I added 50% downscaled versions. Is that enough?

**Comment by ronso0** [comment]
> @Swiftb0y I added 50% downscaled versions. Is that enough?

Let's keep it minimal. The other previews are 640*480
https://github.com/mixxxdj/website/blob/7df911e47d1ee97837016e650d87c0018855c038/theme/templates/pages/screenshots.html#L18

**Comment by m0dB** [comment]
Ok, in that case I guess I should redo the screenshots using a windows sized at 1280x960. I now used fullscreen.

**Comment by m0dB** [comment]
Redone with window instead of fullscreen. It is bigger then 640x because macOS screenshots adds a drop-shadow, but I can crop that if needed.

**Comment by ywwg** [comment]
these look good, can you update the screenshots.html too?

**Review by ywwg — APPROVED** [review]
lgtm

**Comment by ywwg** [comment]
repointed at 2.4 branch

**Pull request merged**
