### PR TITLE
2.4 screenshots

### PR DESCRIPTION
**Pull request by ywwg**
pointing to main branch to get a preview

### CODE REVIEW

**Comment by ywwg** [comment]
pointing back to 2.4

**Comment by ronso0** [comment]
> pointing to main branch to get a preview

Ha, that's the trick!

LGTM, though the "50%" previews can be much smaller, for me they're rendered at ~300x180 px and I can watch them for a few seconds being downloaded.

Tbh, while it may make sense to show the window title bar (now playing text), the white top bars are distracting.
I don't want you to take the screenshots again, so can we simply cut that off?

**Comment by ywwg** [comment]
yup I can crop those

**Review by ronso0 — APPROVED** [review]
Looks good, thank you.

Only issue (and we can't do much about it) is that Shade looks shitty when scaled up.
The other screenshots are excellent.
image

**Pull request merged**
