### PR TITLE
Update screenshots

### LINKED ISSUE #106: screenshot links are small
The images on the screenshots page link to very small images (445x250).

### PR DESCRIPTION
**Pull request by Holzhaus**

### CODE REVIEW

**Comment by Holzhaus** [comment]
Ready to merge!

**Comment by katsar0v** [comment]
Looks fine to me. I guess we will need to update the website as soon as 2.3 stable is out, because the current screenshots are from 2.2 stable?

**Comment by ronso0** [comment]
I'd omit `skin` in the captions and instead write `Here you can find some screenshots of Mixxx' user interface, so called 'skins'.`

Then we can have for example `Shade, Classic theme` or just `Shade Classic`.

**Comment by ronso0** [comment]
tbh it's been a while that I looked at the screenshots on the website.
Looking at the Shade screenshots taken with 4k will raise some questions about the layout:
why is there so much whitespace in the decks? why is there an extra row for the hotcues? why is so much space wasted for the library cover art? ...

I think we should take the screenshots with a resolution close to that each skin was designed for. Like, when the minimum size is 1024px we can take a screenshot with either 1024px or 1280px.
(temporarily changing the minimum size to the desired resolution instead of manually resizing the window..)

**Comment by Holzhaus** [comment]
@katsar0v 
> Looks fine to me. I guess we will need to update the website as soon as 2.3 stable is out, because the current screenshots are from 2.2 stable?

With this PR the screenshot page features both screenshots from 2.2 and 2.3. Check out the deploy preview.

@ronso0 
> I'd omit `skin` in the captions and instead write `Here you can find some screenshots of Mixxx' user interface, so called 'skins'.`
> 
> Then we can have for example `Shade, Classic theme` or just `Shade Classic`.

Hmm, I tried to make that sentence generic because I do think we should add some screenshots of other parts of Mixxx, too (e.g. the preferences). When I check out the website of a software, I always look for screenshots of the settings to see if I can customize it to my needs. Didn't do it in the PR because my GTK theme is ugly.

> tbh it's been a while that I looked at the screenshots on the website.
> Looking at the Shade screenshots taken with 4k will raise some questions about the layout:
> why is there so much whitespace in the decks? why is there an extra row for the hotcues? why is so much space wasted for the library cover art? ...

Yes, I don't know why the library cover art is in a vertical column in Shade.

> I think we should take the screenshots with a resolution close to that each skin was designed for. Like, when the minimum size is 1024px we can take a screenshot with either 1024px or 1280px.
> (temporarily changing the minimum size to the desired resolution instead of manually resizing the window..)

I tried to make all screenshots as similar as possible, i.e. with the same knob/fader settings, the same resolution, roughly the same library view, etc. to make them comparable.

I think we can merge this as is.

**Comment by ronso0** [comment]
> Hmm, I tried to make that sentence generic because I do think we should add some screenshots of other parts of Mixxx, too (e.g. the preferences). When I check out the website of a software, I always look for screenshots of the settings to see if I can customize it to my needs. Didn't do it in the PR because my GTK theme is ugly.

Yup, good idea!

https://github.com/mixxxdj/website/issues/132
https://github.com/mixxxdj/website/issues/133

**Comment by ywwg** [comment]
Hi, thanks for making this change.  Can we choose a different track for the first deck than one by "Joey Negro"?  As part of our work to change nomenclature (https://mixxx.org/news/2020-06-29-black-lives-matter/), it's a bad look to include an artist with a name that he has specifically said he will stop using due to its offensive nature:  https://www.nme.com/news/music/joey-negro-announces-hes-dropped-his-stage-name-2713005

Sorry I didn't catch this before merge.

**Comment by Holzhaus** [comment]
Whoops, sorry, just took a random track from my library. I'm busy tomorrow, I can file a new PR on Sunday.

**Comment by ywwg** [comment]
is it ok if we revert this PR for now? I know it's unlikely anyone will notice but I'd like not to trip on this quite so soon after the post :)

**Comment by ywwg** [comment]
And no worries!  I assumed it was an honest mistake. I've got that hat on so I'm on the lookout for it.

**Comment by Holzhaus** [comment]
> I know it's unlikely anyone will notice but I'd like not to trip on this quite so soon after the post :)

Yeah, that would be embarassing :D

I just realized this only affects the 2.3 screenshots. Make a new PR just about now. Gimme a few minutes.

**Comment by Holzhaus** [comment]
@ywwg In case you didn't see it: https://github.com/mixxxdj/website/pull/134

**Pull request merged**
