### PR TITLE
make 'Free & Open Source' highlighted

### PR DESCRIPTION
**Pull request by katsar0v**
Small change, but this is also my first PR for this repo. I made this section highlighted:

image

### CODE REVIEW

**Comment by Be-ing** [comment]
add to whitelist

**Comment by Holzhaus** [comment]
Thanks. This improves visibility of the donate button. However, I'm not sure about the highlighted section borders and background. How about using a background cover image like we do on the features page instead?

Something like this?
2020-06-10-124922_2637x1585_scrot

**Comment by Holzhaus** [comment]
https://github.com/mixxxdj/website/pull/107

**Comment by katsar0v** [comment]
@Holzhaus am not sure about the photo, but definitely a better highlight! If you could highlight the "donate" button in your PR (with the orange border color), I would vote for it

Does it make sense to move "donate" after download? It would be the second highlight

**Comment by Holzhaus** [comment]
>  If you could highlight the "donate" button in your PR (with the orange border color), I would vote for it

Ok, I applied your change on my branch.

> Does it make sense to move "donate" after download? It would be the second highlight

Good idea, done in #107.

**Comment by katsar0v** [comment]
Thank you @Holzhaus

**Pull request closed without merging**
