### PR TITLE
pages/download: Add testing packages for Windows/macOS

### PR DESCRIPTION
**Pull request by Holzhaus**

### CODE REVIEW

**Comment by Be-ing** [comment]
The preview works for macOS but not Windows.

**Comment by Holzhaus** [comment]
> The preview works for macOS but not Windows.

Yes, because the manifest is wrong. I merged `2.3` into `main`, but unfortunately the macOS package signing timed out and caused a build failure. I restarted the run.

**Comment by Holzhaus** [comment]
Fixed now. I retriggered the deploy preview. Please have a look.

**Comment by Be-ing** [comment]
thanks

**Pull request merged**
