### PR TITLE
build infrastructure blog post: add addendum about sccache

### PR DESCRIPTION
**Pull request by Be-ing**

### CODE REVIEW

**Review by ywwg — APPROVED** [review]
Some of the content in this blog post feels more like documentation than information for our blog-reading audience.  Therefore it might be useful to add it to the mixxx wiki too.  
LGTM

**Comment by Be-ing** [comment]
This isn't documentation, it's telling a story. I don't understand how that would be appropriate for the wiki.

Is there a reason you didn't press merge yet? Do you not have write permission for the website repo?

**Comment by ywwg** [comment]
One of these days I'll get used to our backwards reviewer-presses-merge button, but not today.  sorry

**Comment by Be-ing** [comment]
Thanks for review.

**Pull request merged**
