### PR TITLE
change forum links to https://mixxx.discourse.group/

### PR DESCRIPTION
**Pull request by Be-ing**

### CODE REVIEW

**Comment by Holzhaus** [comment]
We also need a rewrite rule that redirects all request for `/forum/...` to `https://mixxx.discourse.group/...`. Links should still work that way (needed for controller mapping links).

**Comment by Be-ing** [comment]
Can we merge this first then take care of that when we move mixxx.org to Netlify?

**Comment by Be-ing** [comment]
No point bothering to write an Apache rewrite rule when we'll have to redo it for Netlify anyway

**Comment by Holzhaus** [comment]
> Can we merge this first then take care of that when we move mixxx.org to Netlify?

No idea when this will happen. Anyway, we can always do a follow-up PR and change the apache htaccess file later. Merge?

**Review by Holzhaus — APPROVED** [review]
LGTM.

**Pull request merged**
