### PR TITLE
pages: Show latest news on home page

### PR DESCRIPTION
**Pull request by Holzhaus**
Here's my attempt on adding news to the home page. It doesn't look great, so maybe someone with better web design skills wants to improve it a bit before merge.

2020-02-21-122112_1322x1069_scrot

### CODE REVIEW

**Comment by Be-ing** [comment]
@ronso0 any thoughts about the design?

**Review by rryan — APPROVED** [review]
Cool! The only thing I find odd is the date being at the bottom instead of closer to the title. But IMHO we can tweak it in a future PR because it looks good as is.

**Comment by ronso0** [comment]
Until I see the section in context I can't comment on the design, but I'm travelling until march.
Design tweaks can be applied after merge. 

From the preview I see I think the News should be in a more prominent place, maybe at the top?

**Comment by rryan** [comment]
> Until I see the section in context I can't comment on the design, but I'm travelling until march.
> Design tweaks can be applied after merge.

SGTM, I think this is good to go.

**Pull request merged**
