### PR TITLE
Update 2.3 screenshots

### PR DESCRIPTION
**Pull request by Holzhaus**

### CODE REVIEW

**Comment by Swiftb0y** [comment]
Most of the image files don't seem to be used anywhere as part of this PR. Am I just not finding where they are used, or are you planning to use them later?

**Comment by Holzhaus** [comment]
Used on the Screenshots and Features page.

**Review by Swiftb0y — APPROVED** [review]
Thanks, I only looked at the screenshot page, I wasn't aware there were images on the features page as well.

**Comment by ronso0** [comment]
sorry I join in that late..
Is there a reason there are no samplers shown?
Though, good idea not to show the same view with all skins (minimal Tango decks, no effects row in Shade for example)

**Pull request merged**
