### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by Swiftb0y**
Alternative to / fixes #308 while doing the required pelican/jinja changes to not break the build.

### CODE REVIEW

**Comment by Swiftb0y** [comment]
friendly ping

**Comment by ronso0** [comment]
I don't spot anything, CI passes, the Netlify preview looks good :man_shrugging:

**Comment by ronso0** [comment]
Thank you!

**Comment by Swiftb0y** [comment]
Thank you.

**Pull request merged**
