### PR TITLE
use international y-m-d format for news dates

### PR DESCRIPTION
**Pull request by daschuer**
This is a solution for the ambiguous dates issue discussed here: 
https://github.com/mixxxdj/website/pull/67

### CODE REVIEW

**Review by rryan — APPROVED** [review]
Please also update 
https://github.com/mixxxdj/website/blob/d2158047f070afdc214e0e7c1ff629a000f7079f/pages/index.html#L75-L95
and 
https://github.com/mixxxdj/website/blob/d2158047f070afdc214e0e7c1ff629a000f7079f/templates/post.html#L13

**Comment by Holzhaus** [comment]
I had hoped that someone knows how to change the value of `SHORT_DATE_FORMAT` in the settings, so that we don't have to edit all templates manually, but since that's not the case we need to go this route I guess.

**Comment by rryan** [comment]
> I had hoped that someone knows how to change the value of `SHORT_DATE_FORMAT` in the settings, so that we don't have to edit all templates manually, but since that's not the case we need to go this route I guess.

I think this controlled by Django localization. If we were to build the website with locale en-GB I think `SHORT_DATE_FORMAT` would automatically become `d/m/Y`. I don't know how to set it manually.

**Comment by daschuer** [comment]
Done. Merge?

**Comment by Holzhaus** [comment]
What about the index page?

**Comment by Holzhaus** [comment]
> What about the index page?

https://github.com/mixxxdj/website/blob/website/pages/index.html#L81

**Comment by daschuer** [comment]
Done. I had to merge from master first to see the changes. 
Merge now?

**Review by Holzhaus — APPROVED** [review]
Thanks, LGTM.

**Pull request merged**
