### PR TITLE
Add .build directory to .gitignore

### PR DESCRIPTION
**Pull request by uklotzde**
...and omit trailing slash from directories.

### CODE REVIEW

**Comment by Swiftb0y** [comment]
whats producing the `.build` folder for you? I don't have that when I build normally.

**Comment by uklotzde** [comment]
> whats producing the `.build` folder for you? I don't have that when I build normally.

I opened the project in VS Code and the `/.build` directory was generated implicitly.

**Comment by Swiftb0y** [comment]
cannot reproduce. do you have any python/pelican-specific vscode extensions installed (apart from the microsoft stock one)?

**Comment by uklotzde** [comment]
After uninstalling this YAML extension by RedHat the `/.build` directory didn't appear again.

image

**Comment by uklotzde** [comment]
Why is the `__pycache__` directory under version control?

**Comment by Swiftb0y** [comment]
good question. I don't think it mattered yet because all the contained files where just `*.pyc` but its probably better to just put the __pycache__ into the gitignore instead. wydt?

**Pull request closed without merging**
