### PR TITLE
link to Testing wiki page from Downloads page

### PR DESCRIPTION
**Pull request by Be-ing**
This has more details than should clutter the Downloads page.

### CODE REVIEW

**Comment by Be-ing** [comment]
Huh, the deploy preview is not working...

**Comment by Holzhaus** [comment]
Is this still relevant? If so, can you rebase?

**Comment by Be-ing** [comment]
Done

**Review by Holzhaus — COMMENTED** [review]
Is removing the development snapshot section intended?

**Comment by Be-ing** [comment]
Yes, my intention is to direct more users to testing PRs.

**Pull request merged**
