### PR TITLE
show dropdown icons in menu

### PR DESCRIPTION
**Pull request by katsar0v**
I think we should show some arrows:

image

Icon from: https://www.iconfinder.com/icons/186410/arrow_left_previous_icon

### CODE REVIEW

**Comment by ronso0** [comment]
SVG hint:
in Inkscape, save as 'Plain SVG' reduce the file size by omitting all lines specific to Inkscape.

**Comment by ronso0** [comment]
Good idea!
Can you color the arrows like the link fonts? And maybe lower the arrows a bit so they're centered vertically?

**Comment by katsar0v** [comment]
New screenshot:

image

**Review by Holzhaus — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
