### PR TITLE
Fix & update pre-commit

### PR DESCRIPTION
**Pull request by Swiftb0y**
Should fix the failing CI encountered in #287

### CODE REVIEW

**Comment by Swiftb0y** [comment]
I'll take care of fixing codespell tomorrow.

**Comment by daschuer** [comment]
@Swiftb0y friendly reminder

**Comment by Swiftb0y** [comment]
Thanks for the reminder. Codespell acted up and it took me a couple tries to fix.

**Review by daschuer — APPROVED** [review]
Thank you. LGTM

**Pull request merged**
