### PR TITLE
release Mixxx 2.1.4

### PR DESCRIPTION
**Pull request by Be-ing**

### CODE REVIEW

**Comment by Be-ing** [comment]
Waiting for confirmation that the bug is fixed on https://bugs.launchpad.net/mixxx/+bug/1751482 before merging...

**Comment by rryan** [comment]
it'd be nice to re-run the release builds to include a developer ID signature on the macOS build

**Comment by Be-ing** [comment]
Sure, we still haven't announced the release on the website.

**Comment by daschuer** [comment]
Thank you. @Be: Will your write a forums post?

**Pull request merged**
