### PR TITLE
Week 9 progress report

### PR DESCRIPTION
**Pull request by deborahtrez**
Progress report for week 9 :) 
Ready for your review....
@ywwg

### CODE REVIEW

**Comment by deborahtrez** [comment]
I'm not sure why https://github.com/mixxxdj/website/pull/204/commits/49ce424fb003ce7a39eeb114c608bfb09df150ea is included in this pull request.... but this is what i did.

image

**Comment by Holzhaus** [comment]
> I'm not sure why https://github.com/mixxxdj/website/pull/204/commits/49ce424fb003ce7a39eeb114c608bfb09df150ea is included in this pull request.... but this is what i did.
> 
> image
> 

You were on the `paulbloch` branch and created the `week9` branch from there. Therefore it includes all commits from the `paulbloch` branch. If you want to create a new branch based on the `website` branch instead, use:

    $ git checkout website
    $ git checkout -b mynewbranch

or in short:

    $ git checkout -b mynewbranch website

Or even better (based on latest upstream state of the `website` branch):

    $ git fetch upstream
    $ git checkout -b mynewbranch upstream/website


Check: https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging

**Comment by deborahtrez** [comment]
Thank you @Holzhaus . I must have been distracted. 
I have now rectified the issue :)

**Review by Holzhaus — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
