### PR TITLE
release 2.2.1

### PR DESCRIPTION
**Pull request by Be-ing**

### CODE REVIEW

**Comment by daschuer** [comment]
Thank you for the PR. This needs to wait until we have smoke test results from all platforms and finished the release process afterwards.

**Comment by ywwg** [comment]
announced on facebook and twitter

**Comment by Be-ing** [comment]
Thanks for taking care of that.

**Comment by ywwg** [comment]
Can you update the Release Notes link to point at the new forum message? https://mixxx.org/forums/viewtopic.php?p=41693#p41693

**Pull request merged**
