### PR TITLE
Migrate to Pelican static site generator

### PR DESCRIPTION
**Pull request by Holzhaus**
Cactus is no longer maintained, depends on Python 2.7 which is EOL since January and it's not really suited for blogs.
This switches over to the [Pelican](https://github.com/getpelican/pelican) static site generator. It's works with recent Python 3 versions, it's actively maintained and has some neat features like filtering articles by tags, authors or date. I added tags to all existing articles, and also transformed some HTML posts to pure Markdown while I was fixing some Pelican warnings (missing alt attribute on img tags).
 
**TODO**
- [x] Fix video embeds
- [x] Make article metadata CSS responsive

**EDIT:** This mustn't be merged until we switched over mixxx.org to Netlify. Jenkins probably doesn't know that you now need to run `pelican` instead of `cactus build`.

### CODE REVIEW

**Comment by Be-ing** [comment]
Nice work!

**Comment by Be-ing** [comment]
Netlify deploy preview isn't working anymore.

**Comment by Holzhaus** [comment]
> Netlify deploy preview isn't working anymore.

Fixed.

**Comment by Holzhaus** [comment]
Ok, this is ready to merge as soon as we switched mixxx.org to Netlify.

I updated the GitHub Actions post-merge workflow. Please verify it on your local fork:
1. Merge this branch into the website branch, then push the website branch to your fork. If you have a Netlify page for your fork, generate a build hook URL and add it to your repository's secrets (Repository Settings -> Secrets).
2. Then open a Pull Request against the website branch of your fork that adds a new blog post with filename XXXX-XX-XX-somename.html or 2020-XX-XX-somename.html as described in the `README.md` of this branch.
3. Then merge the PR on your fork. Github actions should automatically update the date, commit and push. If you've confogured the NETLIFY_BUILD_HOOK secret, a Netlify deploy will be triggered automatically.

**Comment by Holzhaus** [comment]
I just added a small blogpost explaining the website updates (commit https://github.com/mixxxdj/website/pull/167/commits/59fa163b28070fbc271e5dcc765d4c8a6408bcf9) to the pelican branch and merged the pelican branch to the website branch on my local fork.

As expected, this github workflow was triggered: https://github.com/Holzhaus/mixxx-website/runs/1546740262
That resulted in the autogenerated commit https://github.com/Holzhaus/mixxx-website/commit/913e760c951fe9b3b98f0f3f2b4bc39e1b318441 which in turn triggered a netlify deployment to production on my fork: https://holzhaus-mixxx.netlify.app/news/2020-12-13-improving-our-website/

So everything is working fine

**Comment by Be-ing** [comment]
Nice work! Everything looks the same to me. If there any regressions, they're not obvious to me now and we can fix them afterwards.

**Pull request merged**
