### PR TITLE
Fix text alignment

### PR DESCRIPTION
**Pull request by Holzhaus**

### CODE REVIEW

**Comment by xeruf** [comment]
Can I preview this easily somehow?

**Comment by ronso0** [comment]
https://github.com/mixxxdj/website/blob/website/README.md

**Comment by xeruf** [comment]
You mean clone locally and then build? Yeah, that's why I asked, I didn't set up the environment yet and don't want to do that currently.

**Comment by Swiftb0y** [comment]
staging.mixxx.org? Though I’m not sure how it selects which PRs to show.

**Comment by Holzhaus** [comment]
It always shows the most recently built one.

**Comment by Holzhaus** [comment]
> Can I preview this easily somehow?

    $ mkdir /tmp/venv && python -m venv /tmp/venv && . /tmp/venv/bin/activate && pip install -r requirements.txt && cactus serve

**Comment by Holzhaus** [comment]
Merge?

**Pull request merged**
