### PR TITLE
Fix Zulip link on Contact page.

### PR DESCRIPTION
**Pull request by rryan**

### CODE REVIEW

**Comment by ronso0** [comment]
Thanks!

**Comment by Be-ing** [comment]
For the future, I don't think a trivial PR like this to fix a broken link needs to be reviewed. Go ahead and open a PR if you want to test the Netlify preview, but otherwise I think it's fine if you push directly.

**Comment by ronso0** [comment]
A PR is okay, you can also merge it yourself. Or howelse is everyone notified about a single commit?

**Comment by Be-ing** [comment]
I don't know how you watch GitHub notifications, but the GitHub stream on Zulip has notifications for all commits.

**Comment by ronso0** [comment]
I use the github dashboard, all news about PRs pop up there.
I disabled the github stream as it was too much noise.

**Pull request merged**
