### PR TITLE
change copyright to 2019

### PR DESCRIPTION
**Pull request by ronso0**

### CODE REVIEW

**Comment by daschuer** [comment]
https://epiphany.law/articles/copyright/copyright-dates-single-year-or-range
I think we need to use a range eg. 2000-2019

**Comment by daschuer** [comment]
The written copyright and the sign are redundant. Use only one.

**Comment by ronso0** [comment]
Re year/range
there are different opinions, and AFAICT the year of the first publication would be sufficient.
however, a range indicates that the project is maintained.
I'll change it to **&copy; 2001-2019 Mixxx Development Team**

**Review by daschuer — APPROVED** [review]
Thank you. LGTM

**Comment by Pegasus-RPG** [comment]
In the future, we should just use `<?php echo date('Y');?>` so it is always up-to-date. That does require of course changing the file extension to .php and adjusting every place it's included.

**Comment by ronso0** [comment]
> In the future, we should just use `<?php echo date('Y');?>` so it is always up-to-date. That does require of course changing the file extension to .php and adjusting every place it's included.

sure, what's necessary to implement this?

**Comment by Be-ing** [comment]
I'd rather not introduce PHP to the static website. A little JS could take care of it though

**Comment by sblaisot** [comment]
javascript in the browser is client-side. You have absolutely no idea of the date on the client browser. (well, at least not too far away or it will break TLS negociation).

It surely is good enough to print a copyright date on the site but it should be kept in mind as it could cause great problems in another context.

**Comment by sblaisot** [comment]
Does the server support [Server-Side includes](https://en.wikipedia.org/wiki/Server_Side_Includes) ?

For example for [apache](https://httpd.apache.org/docs/current/howto/ssi.html) or [nginx](http://nginx.org/en/docs/http/ngx_http_ssi_module.html)

Simply add in your html file
```
<!--#config timefmt="%Y" -->
<!--#echo var="DATE_LOCAL" --> 
```

**Pull request merged**
