### PR TITLE
Delete trailing whitespace

### PR DESCRIPTION
**Pull request by uklotzde**
This should be detected and either prevented or fixed by autoformatting tools.

### CODE REVIEW

**Review by Swiftb0y — APPROVED** [review]
LGTM. what autoformat tool do you suggest that is capable of this ootb?

**Comment by uklotzde** [comment]
> LGTM. what autoformat tool do you suggest that is capable of this ootb?

I use [prettier](https://github.com/uklotzde/djio/blob/99d6e231663b1c2dc5139a998f80cc39ffbf506b/.pre-commit-config.yaml#L68C22-L68C22) for this purpose.

**Comment by Swiftb0y** [comment]
yeah makes sense. why does this file have a `.md` extension anyways?

**Comment by Holzhaus** [comment]
Because this are markdown files with a YAML metadata part. 😅

**Comment by Swiftb0y** [comment]
right, but there is no markdown in the file, soo couldn't it just be plain yaml? Or is that yaml-in-markdown schema required for the static site generator to pick it up appropriately?

**Comment by Holzhaus** [comment]
> Or is that yaml-in-markdown schema required for the static site generator to pick it up appropriately?

Yes IIRC.

**Pull request merged**
