### PR TITLE
plugins/news: Make post time optional and fall back to "now" on error

### PR DESCRIPTION
**Pull request by Holzhaus**

### CODE REVIEW

**Comment by Holzhaus** [comment]
This is a minor fix to make branches without a valid data build. A warning will still be displayed as before. Merge?

**Comment by Holzhaus** [comment]
@Be-ing Merge?

**Comment by ronso0** [comment]
LGTM, works as intended. (but I have no py knowledge unfortunately..)

**Comment by Holzhaus** [comment]
> (but I have no py knowledge unfortunately..)

basically it just tries to parse the date in the `YYYY-MM-DD HH:mm:ss` format, and if that throws an error it tries `YYYY-MM-DD`, and if that also throws an error it just uses the current date and logs a warning.

**Comment by ronso0** [comment]
... I thought so but I have no idea what can go wrong.

If you consider the change trivial and rather unlikely to cause a regression I can of course merge it now.

**Comment by Holzhaus** [comment]
I think it's unlikely that this causes a regression, yes.

**Pull request merged**
