### PR TITLE
Update download page for 2.4.1

### PR DESCRIPTION
**Pull request by daschuer**

### CODE REVIEW

**Comment by daschuer** [comment]
We have no https://downloads.mixxx.org/releases/2.4.1/manifest.json :-/

**Comment by ronso0** [comment]
Did you overlook #350 ?

**Comment by ronso0** [comment]
Oh, you set 2.4.0 as previous. I thought we link to the previous major version.

**Comment by ronso0** [comment]
> We have no https://downloads.mixxx.org/releases/2.4.1/manifest.json :-/

How is that created? Not manully I hope...

**Comment by daschuer** [comment]
> Did you overlook https://github.com/mixxxdj/website/pull/350 ?

Yes sorry. I close this. I was unsure about the previous version. I will close this in favor of your one.

**Comment by ronso0** [comment]
> I was unsure about the previous version.

I'm not sure either, it's just I assumed we link to the previous major version in case users like to revert to a certain version with different features (in case a new feature is a regression for specific use cases https://xkcd.com/1172/).

Either way, all previous versions are available at http://downloads.mixxx.org/releases/

**Pull request closed without merging**
