### PR TITLE
Netlify: Add security headers

### PR DESCRIPTION
**Pull request by Holzhaus**
Related Zulip discussion:
https://mixxx.zulipchat.com/#narrow/stream/109121-core-team/topic/HTTPS.20on.20downloads.2Emixxx.2Eorg/near/215163005

TODO:
- [x] Fix discourse embeds (?)
- [x] Fix YouTube embeds
- [x] Fix missing background images

### CODE REVIEW

**Comment by Holzhaus** [comment]
Ok, I think is this ready. Please test. The discourse embeds can't be tested properly using the deploy preview. We probably need to merge and hope for the best, and revert/fix if it doesn't work.

**Comment by ronso0** [comment]
regular navigation works. https enforcement, too.

 The discourse embeds are the only crucial point (we can't test) ?

**Comment by Holzhaus** [comment]
> regular navigation works. https enforcement, too.
> 
> The discourse embeds are the only crucial point (we can't test) ?

No we can't, because it checks the referrer and our deploy previews have a different URL than the actual website...

**Comment by ronso0** [comment]
*thunbs pressed!*

**Comment by Holzhaus** [comment]
> _thunbs pressed!_

I just realized we won't know if this works until we switch our website to netlify :(

**Pull request merged**
