### PR TITLE
Add various fixes and pre-commit support

### PR DESCRIPTION
**Pull request by Holzhaus**

### CODE REVIEW

**Comment by Holzhaus** [comment]
Merge? This fixes some typos on the website as well.

**Comment by ronso0** [comment]
LGTM, except I can't judge the yml/yaml files.

**Comment by Holzhaus** [comment]
OK, let's merge then. Worst that can happen is that the hooks fail and we need to ignore them until they are fixed.

**Comment by ronso0** [comment]
Alrigth.

**Pull request merged**
