### PR TITLE
Announce the 2.3.2 release

### PR DESCRIPTION
**Pull request by daschuer**
This can be merged only after we have tagged the release.

### CODE REVIEW

**Comment by ronso0** [comment]
> after we have tagged the release

Marked as draft until tha is true.

**Comment by daschuer** [comment]
Now it is true.

**Review by ronso0 — APPROVED** [review]
LGTM, thank you!

I can take care of the release announcement tomorrow night or the day after.
If someone can do this earlier please go ahead.

**Comment by Holzhaus** [comment]
> I can take care of the release announcement tomorrow night or the day after.
> If someone can do this earlier please go ahead.

I pushed a short release announcment into this branch.

**Comment by daschuer** [comment]
Thank you very much.

**Review by ywwg — APPROVED** [review]

**Comment by Holzhaus** [comment]
Merge?

**Comment by Holzhaus** [comment]
Too late, now it's already Feb 1. Converting to draft. I need to fixup the commit with a hard-coded date.

**Comment by Holzhaus** [comment]
OK, ready to merge again, this time with hard-coded date because nobody merged this in time.

Next time, let's please not tag a release before the release announcement is ready, then merge it immediately after tagging.

**Comment by uklotzde** [comment]
If no one else is willing to merge this PR one day after the official release date then I will do it now. Thanks for the separate release announcement, Jan! LGTM

**Pull request merged**
