### PR TITLE
Add News pages

### PR DESCRIPTION
**Pull request by Holzhaus**
The [blogspot site](https://mixxxblog.blogspot.com/) linked on the website is unmaintained.

IMHO it makes more sense to have this integrated into the main website.

I added support for a news page and migrated the old blog posts using the Atom feed. I also added the newer release announcements from the forum posts.

What's still missing is an RSS/Atom feed, but we can add this later on. If this is merged, someone could add a post to the old blog that links to the new news page.

### CODE REVIEW

**Comment by Holzhaus** [comment]
OK, I added an Atom feed.

**Comment by Be-ing** [comment]
Can you get the `/news/` index page to show the contents of the most recent post?

**Comment by Holzhaus** [comment]
Done.

2020-02-15-22-00-02_1366x768

**Comment by Be-ing** [comment]
The links to older news pages are broken when I run `cactus serve` locally:
image

**Comment by Be-ing** [comment]
The URLs work without the `.html` extension:
image

**Comment by Holzhaus** [comment]
Fixed.

**Comment by Holzhaus** [comment]
@Be-ing please check again if everything works nicely now.

**Comment by Be-ing** [comment]
Old assets like screenshots still link to blogspot.com. Could you add them as assets to this repository and using relative links?

**Comment by Holzhaus** [comment]
> Old assets like screenshots still link to blogspot.com. Could you add them as assets to this repository and using relative links?

Should be fixed now.

**Comment by Be-ing** [comment]
Looks good when I test it locally, but the build server is now failing. I thought the build for the PR might have been a one-off failure so I went ahead and merged this PR, but the build to deploy to the main website didn't work either. I don't know what's wrong from the [build log](https://builds.renegadetech.mixxx.org/job/website/55/console).

**Comment by Holzhaus** [comment]
java.lang.NoClassDefFoundError: Could not initialize class hudson.slaves.SlaveComputer

This looks unrelated. I don't see what my PR has to do with Java.

**Comment by Be-ing** [comment]
It might be related to the recent build server maintenance.

**Comment by daschuer** [comment]
The news date appears to me as 02/04/2020

This is highly ambiguous, because UK and US English swap the day and month.

I suggest to move to the international 2020-04-02 format like we did in the press page.

What do you think?

**Comment by Holzhaus** [comment]
We should set `SHORT_DATE_FORMAT` to the desired value then: https://docs.djangoproject.com/en/dev/ref/settings/#std:setting-SHORT_DATE_FORMAT

I'm not sure how to do this in cactus, since the tools has been discontinued and the documentation is down.

**Pull request merged**
