### PR TITLE
pages/download: Expand section if URL contains an anchor

### PR DESCRIPTION
**Pull request by Holzhaus**
This expands the appropriate section automatically when using a link like: https://mixxx.org/download/#stable-macos

### CODE REVIEW

**Comment by ronso0** [comment]
hmm.. it somehow "works" i.e. opens a container but the link https://mixxx.org/download/#stable-macos opens Ubuntu for me

**Comment by ronso0** [comment]
..as does https://mixxx.org/download/#stable-windows

**Comment by Holzhaus** [comment]
> hmm.. it somehow "works" i.e. opens a container but the link https://mixxx.org/download/#stable-macos opens Ubuntu for me

The code only runs when the page is loaded. Are you sure it really reloads the page? If you edit the URL fragment when you're already on the download site, the browser won't reload (press F5 to work around this).

**Comment by ronso0** [comment]
Yes, opening https://mixxx.org/download/#stable-macos always opens the Ubuntu.
https://mixxx.org/download/#stable-windows too

**Comment by ronso0** [comment]
/#fedora-stable works, though.
Seems it's just Windows and macOS that don't.

**Comment by ronso0** [comment]
maybe because 'linux' user agent is detected?

**Comment by Holzhaus** [comment]
> maybe because 'linux' user agent is detected?

Ah yes, that's true. Should be fixed now.

**Comment by ronso0** [comment]
yup, works!

**Pull request merged**
