### PR TITLE
pages/download: Make donation section more prominent

### PR DESCRIPTION
**Pull request by Holzhaus**
https://mixxx.zulipchat.com/#narrow/stream/109695-_support/topic/.5BOfftopic.5D.20Thank.20you.20for.202.2E3.20beta/near/200297719

### CODE REVIEW

**Comment by ronso0** [comment]
LGTM!

**Review by xeruf — COMMENTED** [review]
Something here doesn't quite match up. You added two closing divs but only one opening?

**Comment by Holzhaus** [comment]
Yes, it was missing before.

**Comment by Holzhaus** [comment]
Merge?

**Pull request merged**
