### PR TITLE
Cleanup top bar

### PR DESCRIPTION
**Pull request by radusuciu**
Took a crack at this issue, there are some things to fix likely but I wanted to open request to solicit comments.

before:
image

after:
image

### CODE REVIEW

**Comment by Be-ing** [comment]
This is looking better. I think we could use a redesign of the site navigation.

Using two words for "Support & Community" is bugging me. How about changing that to just "Support" and renaming the "Get Involved" page to "Community"?

**Comment by ronso0** [comment]
Yes, great!

It's also nice that now **DJ Your Way** is close to "Free and open source DJ software ..."

Only one thing that's irritating: the font of the top links is decreased in steps, and the smallest size (just before the hamburger menu toggle appears) is actually to small IMO. I think the top links' font shouldn't be smaller than the main paragraphs' font.
I think the when the screen is small and the font size is decreased, those three links are small enough to use 2 lines right next to the logo.

**Comment by ronso0** [comment]
@Be-ing 
"Community" should imply "Support" ;)
For me, "Community" would go more along the lines of "DJ your way", "free & open source" etc.

Looking closer, the incosistent links at the top and in the footer are a bit irritating, kind of reminds of the wiki: I know there was a site about how to get involved but where was that link again?
That said, maybe the footer should -apart from "Pages" main navigation- only show links that don't appear in the top bar? 
Pages * Community links * About

**Comment by Be-ing** [comment]
> "Community" should imply "Support" ;)

Yes, and I don't think most people think that way.

Do we even need a footer? Can we get rid of it?

**Comment by radusuciu** [comment]
> 
> 
> This is looking better. I think we could use a redesign of the site navigation.
> 
> Using two words for "Support & Community" is bugging me. How about changing that to just "Support" and renaming the "Get Involved" page to "Community"?

I agree. We could probably fit 4 top-level links instead of 3 with that change - if there were 4 things that make sense. Currently "Get Involved" gets the chop somewhat..

> 
> 
> @Be-ing
> "Community" should imply "Support" ;)
> For me, "Community" would go more along the lines of "DJ your way", "free & open source" etc.
> 
> Looking closer, the incosistent links at the top and in the footer are a bit irritating, kind of reminds of the wiki: I know there was a site about how to get involved but where was that link again?
> That said, maybe the footer should -apart from "Pages" main navigation- only show links that don't appear in the top bar?
> Pages * Community links * About

> 
> 
> > "Community" should imply "Support" ;)
> 
> Yes, and I don't think most people think that way.
> 
> Do we even need a footer? Can we get rid of it?

So are you guys leaning towards Support or Community?

In my opinion the footer is useful and repetition is okay, but I also think we could do things without it and just consolidate things into existing pages. I think it could also be made to look a little better.

Btw, we need a higher quality screenshot - especially for higher density displays. I also saw some talk on Zulip about a video splash -- that would be really nice in the future.

**Comment by ronso0** [comment]
btw, the social icons seem a bit lost in that corner.
could they move over to the right upper corner of the screenshot so we have all in one place?

**Comment by ronso0** [comment]
> So are you guys leaning towards Support or Community?

To me "Community" sounds more welcoming, but "Support" is what it's about for people coming to Zulip or the forums (in the first place they're looking for help) so I'm okay with it.

> Do we even need a footer? Can we get rid of it?

I suggest to keep the footer for quick links, much quicker than going through the paragraphs on the Support page
* Site overview / Pages: home, download, feature, support
* Support: link list
* About: contact (for legal reasons I guess), press (Manual should be in Support column)

**Comment by Be-ing** [comment]
> So are you guys leaning towards Support or Community?

Both. Support is where to find help. Community is where to get involved.

**Comment by radusuciu** [comment]
Alright, so to summarize:
- separate page for "Community" which will mostly be the "Get Involved Page"
- separate page for "Support" which will mostly be the same as the current page
- tweak footer as discussed above
- move social links

I've experimented with a few other small tweaks that I think will make the website a little more "sharp", but I will leave those for another pull request.

Thank you for your feedback and for being so receptive to changes! I enjoy contributing to Mixxx and this is a good fit for my skills and more importantly availability.

**Comment by ronso0** [comment]
For the hover effect of navbar items, let's use the same as for regular links: #ffB000

**Comment by Be-ing** [comment]
This is looking good! How about renaming the URI for the "get-involved" page to "contribute"? Also, I think the link at the top of the page for non-programmers is awkward. How about rearranging the page so the "DJs" and "Software Developers" sections are in columns side-by-side? Or moving the "DJs" section to the top above "Software Developers".

**Comment by ronso0** [comment]
Funny I didn't noticed that "Not a coder?" link until now.. it was placed in a blind spot in the upper rigth corner I guess

:+1: for removing that link and putting DJs/Translators/Graphic Artists and Software Developers side by side.

But I think we should focus on improving the top bar, otherwise we'll end up with an endless wishlist for the content area.

**Comment by radusuciu** [comment]
I will rename the page from get-involved to contribute and create a redirect via whatever method is possible with Cactus.

I agree with your points above regarding the"Community" page but I think these concerns are best addressed in a separate PR. The reason I moved the "Not a coder?" link was because it wasn't floating very nicely during page resizes.

What's left to do (from my perspective) is to make sure that the menu is legible and usable at all resolutions, and to also re-work the footer a little bit. I'm having a bit of trouble with the social media links though - tbh bringing them into or closer to the main container isn't very attractive.

**Comment by ronso0** [comment]
IMO this could look alright if the navbar items are spread equally, not with a fixed margin.
This is just before the social icons are hidden ant the link font is decreased (~770px width):
image

**Comment by ronso0** [comment]
Screenshot_2019-10-09_19-34-40

**Comment by radusuciu** [comment]
I like the second one

**Comment by ronso0** [comment]
yeah, and it'll look even better if all the links incl. the logo were sitting a bit lower in that black margin.
like top/bottom black space is 1/2

**Comment by radusuciu** [comment]
Note: still on this, but haven't had time to finish due to work being busy

**Comment by Holzhaus** [comment]
I like the second version, too.

We now have a blog integrated into our websites. Maybe we shoud rename "Features" to "About" and put it there. Or we Rename contributing to "Development" and add a link on that page?

**Comment by radusuciu** [comment]
image

**Comment by radusuciu** [comment]
It's been a while, but any interest in merging? Changes to menu items? @ronso0

**Comment by Holzhaus** [comment]
I'd be in favor of the cleanup, but now the news become hard to find.

**Comment by Be-ing** [comment]
It feels strange to me that the width of the top bar is now constrained by the rest of the contents' width.

**Comment by radusuciu** [comment]
> It feels strange to me that the width of the top bar is now constrained by the rest of the contents' width.

This could be addressed by making the navbar an actual bar perhaps, like this:

image
image

**Comment by Be-ing** [comment]
Yes that looks better IMO.

**Comment by ronso0** [comment]
Actually I considered the compact top bar _the_ feature of this PR. Stretching it over the entire width makes the bar scattered again and doesn't look good IMO.
Can we remove the Features link? We could put it below the brief features intro paragraph on the main page, where that duplicate, bright download link is now.
Don't want to engage a complete clean-up here, it's just about the top bar..

**Comment by radusuciu** [comment]
> Actually I considered the compact top bar _the_ feature of this PR. Stretching it over the entire width makes the bar scattered again and doesn't look good IMO.

I think this would still represent a simplification though. Currently there is not only spread but also too many menu items and of different sizes.

> Can we remove the Features link? We could put it below the brief features intro paragraph on the main page, where that duplicate, bright download link is now.

Agreed. Perhaps we can reproduce this pattern for the News and Community front-page sections (without removing it from them top navigation though) later. I have some ideas for how to do this but as you've identified below, probably better to keep the scope of these pull requests small.

> Don't want to engage a complete clean-up here, it's just about the top bar..

Also agreed, I think there is a more modern design that we're helping emerge here but that can be addressed separately.

**Comment by Be-ing** [comment]
I'm not sure I'd want to remove "Features" from the top bar. When I look at the website for software I'm considering using, the first thing I want to see is a features or screenshots page.

**Comment by ronso0** [comment]
Right now it looks scattered, a bit like 'not associated' IMO.
I suggest we either stretch both the header and image area below, or keep both at content width.

**Comment by ronso0** [comment]
> I'm not sure I'd want to remove "Features" from the top bar. When I look at the website for software I'm considering using, the first thing I want to see is a features or screenshots page.

If we can't agree on if and what to remove items from the top bar, then let's try to have a compact 2-row top section. Maybe that's possible without it looking crammed.

**Comment by radusuciu** [comment]
I'd like to show you another version with a few more tweaks that maybe you'll prefer. Willing to implement whatever the consensus is though. Thanks for reviewing!

**Comment by ronso0** [comment]
> I'm not sure I'd want to remove "Features" from the top bar. When I look at the website for software I'm considering using, the first thing I want to see is a features or screenshots page.

True, but I start looking for such a quick link _only_ if the first scroll down the page doesn't reveal a feature list or -like we have it now- a brief feature intro with a link to further info.
I think that would suit very well.

I'd like to remove the duplicate Download link, anyway. It feels redundant and a bit like begging for attention.

**Comment by radusuciu** [comment]
image
image

**Comment by ronso0** [comment]
Hmm for me it feels like we were already one step further in improving the design:
image

Item order should be
News * Download * Features * Support * Contribute

From the Screenshots it looks like all that + the logo would fit above the main image if the social media icons were stacked vertically. In case the top links don't fit in I suggests to make the logo slightly smaller.
Then I'd consider this mergable.

**Comment by radusuciu** [comment]
Alright. I made the social icons as big as they could be without sticking out of the navbar element.

image

Note that at some point I added a hover color to the navbar. You may not have noticed if you didn't build, or have a chance to test on the staging site, so here it is in case it's not desired:
image

**Comment by Be-ing** [comment]
>  News * Download * Features * Support * Contribute

I'd suggest:
Download, Features, News, Support, Contribute

**Comment by ronso0** [comment]
why?
**Download** is obvious, people active look for it, no need to list it first, and we have huge DOWNLOAD buttons.
**News** otoh should be more prominent to promote it IMO.

**Comment by Holzhaus** [comment]
Idea: we could put a download button at top right of the bar.

We could also add an "About" item that has a drop down menu including "features". I can add that in a follow up PR if you want.

**Comment by radusuciu** [comment]
> Idea: we could put a download button at top right of the bar.
> 
> We could also add an "About" item that has a drop down menu including "features". I can add that in a follow up PR if you want.

That could be nice, but also potentially busy unless we widen the navbar and some elements of the page - I'm in favor of these changes as well. However, I do think these are better addressed in a separate PR, given that the current state stands on its own and is an improvement I believe.

As for order, I think both are fine, but I lean towards News first for these same reasons:

> Download is obvious, people active look for it, no need to list it first, and we have huge DOWNLOAD buttons.

there is indeed a large green download button just above the fold. Also, order may soon be moot if we end up going in the direction @Holzhaus mentioned above

**Comment by Be-ing** [comment]
> We could also add an "About" item that has a drop down menu including "features". I can add that in a follow up PR if you want.

What else would be in that submenu?

**Comment by Holzhaus** [comment]
> What else would be in that submenu?

Press and contact.

Another one would be "Community & Support" with subitems Manual, Forums, Wiki and "Get Involved".

**Comment by ronso0** [comment]
And in the mobile view it would be good if the submenu items would be subsections in the menu list without having to open a submenu.

**Comment by ronso0** [comment]
When reducing the window width I still get cropped social icons just before the stylesheet flips to `@media only screen and (max-width: 960px)`. Below 960px the social icons disappear.
image

**Comment by radusuciu** [comment]
> 
> 
> When reducing the window width I still get cropped social icons just before the stylesheet flips to `@media only screen and (max-width: 960px)`. Below 960px the social icons disappear.
> image

Okay, I'll take a look and fix, thanks for testing. What browser?

**Comment by ronso0** [comment]
firefox, latest Version

**Comment by radusuciu** [comment]
Closing in favor of #97 which solves all of these issues and more!

**Pull request closed without merging**
