### PR TITLE
More HTTPS, fix mixed content

### PR DESCRIPTION
**Pull request by ishitatsuyuki**

### CODE REVIEW

**Comment by Be-ing** [comment]
Thanks for bringing this up. I think this will likely cause merge conflicts with #8 and #10, so let's wait until those are merged before merging this.

**Comment by sblaisot** [comment]
Why not using protocol agnostic links ?
https://www.paulirish.com/2010/the-protocol-relative-url/

use //domaine.com/filepath instead of https://domaine.com/path. This way, it will work with both http and httpd depending on the version you browse.

**Comment by ishitatsuyuki** [comment]
Why using that? Loading HTTPS on HTTP is fine IIRC.

**Comment by rryan** [comment]
> Why using that? Loading HTTPS on HTTP is fine IIRC.

We may need to disable HTTPS at some point in the future (e.g. during server maintenance or migration) and it would be nice to have that not break things.

**Comment by daschuer** [comment]
Is this one still relevant? Can we close it?

**Comment by ishitatsuyuki** [comment]
Mixed content is still a thing. Given that this is unblocked, should I rebase?

**Comment by ishitatsuyuki** [comment]
Closing due to inactivity.

**Pull request closed without merging**
